geartracker/urls.py
from django.conf.urls import *
from django.views.generic import TemplateView

from geartracker.views import *

urlpatterns = patterns('',
    url(r'^$',
        view = index,
        name = 'geartracker'
    ),
    url(r'^all/$',
        view=ItemListView.as_view(),
        name='geartracker_item_list'
    ),
    url(r'^category/$',
        view=CategoryListView.as_view(),
        name='geartracker_category_list'
    ),
    url(r'^category/(?P<slug>[-\w]+)/$',
        view=CategoryDetailView.as_view(),
        name='geartracker_category_detail'
    ),
    url(r'^category/(?P<category>[-\w]+)/(?P<slug>[-\w]+)/$',
        view=TypeDetailView.as_view(),
        name = 'geartracker_type_detail'
    ),
    url(r'^tags/$',
        view=TemplateView.as_view(template_name='geartracker/tag_list.html'),
        name='geartracker_tag_list'
    ),
    url(r'^tags/(?P<slug>[-\w]+)/$',
        view=TagDetailView.as_view(),
        name='geartracker_tag_detail'
    ),
    url(r'^list/$',
        view=ListListView.as_view(),
        name='geartracker_list_list'
    ),
    url(r'^list/(?P<slug>[-\w]+)/$',
        view=ListDetailView.as_view(),
        name='geartracker_list_detail'
    ),
    url(r'^(?P<slug>[-\w]+)/$',
        view=ItemDetailView.as_view(),
        name='geartracker_item_detail'
    ),
)

geartracker/models.py
from django.db import models

from taggit.managers import TaggableManager
from sorl.thumbnail import ImageField

from geartracker.managers import PublicListManager, ArchivedItemManager
from geartracker.mass import metric, imperial


class Category(models.Model):
    """ Model representing a category """
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name_plural = "categories"
        ordering = ('name',)

    @property
    def number_items(self):
        return len(self.item_set.all())

    def __unicode__(self):
        return self.name


class Type(models.Model):
    """ Model representing a type """
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category)

    class Meta:
        ordering = ('category', 'name',)

    @property
    def number_items(self):
        return len(self.item_set.all())

    @property
    def separator(self):
        return '::'

    def __unicode__(self):
        return u'%s %s %s' % (self.category, self.separator, self.name)


class Item(models.Model):
    """ Model representing an item """
    make = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    weight = models.PositiveIntegerField(verbose_name="Weight (grams)",
                                         help_text="Weight in grams only. \
                                                    Do not include units.")
    acquired = models.DateField(help_text="The date on which this item was \
                                           acquired.")
    type = models.ForeignKey(Type)
    size = models.CharField(max_length=30, blank=True)
    link = models.URLField(blank=True, null=True,
                           help_text="A URL to the manufacturer's page for \
                                      the item.")
    review_url = models.URLField(blank=True, null=True,
                                 help_text="A URL to a review of the item.")
    notes = models.TextField(blank=True, help_text="Any notes on the item.")
    image = models.ImageField(upload_to='geartracker/images/gear/', blank=True)
    category = models.ForeignKey(Category, editable=False)
    tags = TaggableManager(blank=True)
    related = models.ManyToManyField("self", blank=True)
    archived = models.BooleanField(default=False,
                                   help_text="Archived items are not publicly \
                                              viewable.")
    objects = ArchivedItemManager()

    class Meta:
        ordering = ('make', 'model')

    def __unicode__(self):
        if self.size:
            return u'%s %s (%s)' % (self.make, self.model, self.size)
        else:
            return u'%s %s' % (self.make, self.model)

    @models.permalink
    def get_absolute_url(self):
        return ('geartracker_item_detail', None, {'slug': self.slug})


    @property
    def name(self):
        return self.__unicode__()

    @property
    def metric_weight(self):
        return metric(self.weight)

    @property
    def imperial_weight(self):
        return imperial(self.weight)

    def save(self, *args, **kwargs):
        # Set the item's category to whatever the type's category is.
        self.category = self.type.category
        # Call the real save.
        super(Item, self).save(*args, **kwargs)


class ListItem(models.Model):
    """ Model representing an item in a gear list """
    CARRY_CHOICES = (
        ('packed', 'Packed'),
        ('worn', 'Worn'),
    )
    item = models.ForeignKey(Item)
    list = models.ForeignKey('List')
    quantity = models.PositiveIntegerField(default=1)
    type = models.CharField(max_length=6, choices=CARRY_CHOICES)

    def __unicode__(self):
        return u'%s (%sx)' % (self.item, self.quantity)

    @property
    def total_weight(self):
        return self.quantity * self.item.weight

    @property
    def total_metric_weight(self):
        return metric(self.quantity * self.item.weight)

    @property
    def total_imperial_weight(self):
        return imperial(self.quantity * self.item.weight)


class List(models.Model):
    """ Model representing a gear list """
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    location = models.CharField(max_length=200, blank=True)
    start_date = models.DateField()
    end_date = models.DateField()
    trip_report = models.URLField(blank=True, null=True,
                                  help_text="A URL to a trip report.")
    public = models.BooleanField(default=True)
    items = models.ManyToManyField(Item, through=ListItem)
    objects = PublicListManager()

    class Meta:
        ordering = ('-start_date', 'end_date')

    def __unicode__(self):
        return self.name

    @models.permalink
    def get_absolute_url(self):
        return ('geartracker_list_detail', None, {'slug': self.slug})


    def clean(self):
        from django.core.exceptions import ValidationError
        # Trip end date must be greater than start date
        if self.end_date < self.start_date:
            raise ValidationError("The end date must be greater than or equal \
                                  to the start date.")

    def add_weight(self, items):
        total_weight = 0
        for item in items:
            total_weight += item.total_weight
        return total_weight

    @property
    def packed_weight(self):
        list_items = ListItem.objects.filter(list=self, type='packed')
        return self.add_weight(list_items)

    @property
    def packed_metric_weight(self):
        return metric(self.packed_weight)

    @property
    def packed_imperial_weight(self):
        return imperial(self.packed_weight)

    @property
    def worn_weight(self):
        list_items = ListItem.objects.filter(list=self, type='worn')
        return self.add_weight(list_items)

    @property
    def worn_metric_weight(self):
        return metric(self.worn_weight)

    @property
    def worn_imperial_weight(self):
        return imperial(self.worn_weight)

    @property
    def total_weight(self):
        list_items = ListItem.objects.filter(list=self)
        return self.add_weight(list_items)

    @property
    def total_metric_weight(self):
        return metric(self.total_weight)

    @property
    def total_imperial_weight(self):
        return imperial(self.total_weight)

geartracker/templates/geartracker/all_items.html
{% extends "geartracker/base_geartracker.html" %}
{% block title %}All Gear{% if is_paginated %} | Page {{ page }}{% endif %}{% endblock %}
{% block entry %}

<h1>All Gear</h1>

{% include "geartracker/items_list.html" %}

{% if is_paginated %}
<ul class="page-list">
    {% for pages in page_range %}
    <li {% if page = pages %}class="current"{% endif %}><a href="{% url items_paginated page=pages %}" title="Page {{ pages }}">{{ pages }}</a></li>
    {% endfor %}
</ul>
{% endif %}
{% endblock %}

geartracker/templates/geartracker/base.html
{% extends "base.html" %}
{% block title %}Gear Tracker{% endblock %}
{% block content %}

<ul id="gear-nav">
    <li><a href="{% url items_view %}" title="View a list of all gear">All Gear</a></li>
    <li><a href="{% url lists_view  %}" title="View all gear lists">Gear Lists</a></li>
    <li><a href="{% url geartracker.views.categories_view 'ies' %}" title="View a list of categories">Categories</a></li>
    <li><a href="{% url tags_view %}" title="View a list of tags">Tags</a></li>
</ul>

<div id="entry"{% block entry_class %}{% endblock %}>
{% block entry %}
{% endblock %}
</div>
{% endblock %}

geartracker/templates/geartracker/base_geartracker.html
{% extends "base.html" %}
{% block title %}Gear Tracker{% endblock %}
{% block description %}A database of gear for wilderness travel{% endblock %}
{% block body_class %}geartracker{% endblock %}

geartracker/templates/geartracker/category_list.html
{% extends "geartracker/base_geartracker.html" %}

{% block title %}Categories | {{ block.super }}{% endblock %}
{% block description %}Gear categories{% endblock %}
{% block body_id %}geartracker-list-list{% endblock %}

{% block content %}
    <h1>Categories</h1>

    <ul class="categories">
    {% for category in category_list %}
        <li><a href="{% url "geartracker_category_detail" slug=category.slug %}" title="View all gear in {{ category }}">{{ category|capfirst }}</a>
            {% if category.type_set.all %}
            <ul>
                {% for type in category.type_set.all %}
                <li><a href="{% url "geartracker_type_detail" category=category.slug slug=type.slug %}" title="View all gear in {{ type.name }}">{{ type.name|capfirst }}</a></li>
                {% endfor %}
            </ul>
            {% endif %}
        </li>
    {% endfor %}
    </ul>
{% endblock %}

geartracker/templates/geartracker/index.html
{% extends "geartracker/base_geartracker.html" %}

{% block body_id %}geartracker-home{% endblock %}

{% block content %}
    {% if item_list %}
    <div class="recent-gear">
        <h1>Recent Gear</h1>
        {% with object_list=item_list %}
            {% include "geartracker/includes/list_items.html" %}
        {% endwith %}
    </div>
    {% endif %}

    {% if list_list %}
    <div class="recent-list">
        <h1>Recent Gear Lists</h1>
        {% include "geartracker/includes/list_lists.html" %}
    </div>
    {% endif %}
{% endblock %}

geartracker/templates/geartracker/item_detail.html
{% extends "geartracker/base_geartracker.html" %}

{% load thumbnail %}

{% block title %}{{ item }} | {{ block.super }}{% endblock %}
{% block description %}Details of {{ item.make }}'s {{ item.model }} ({{ item.metric_weight }}, {{ item.imperial_weight }}){% endblock %}
{% block body_class %}geartracker-item geartracker-item-category-{{ item.category.slug }} geartracker-item-type-{{ item.type.slug }}{% endblock %}
{% block body_id %}geartacker-item-{{ item.id }}{% endblock %}

{% block content %}
    {% spaceless %}
    <h1>
    {% if item.link %}
        <a class="product-link" href="{{ item.link }}" title="Visit {{ item.make }}'s page for the {{ item.model }}.">{{ item }}</a>
    {% else %}
        {{ item }}
    {% endif %}
    </h1>
    {% endspaceless %}

    {% if perms.geartracker.change_item %}
    <a title="Edit {{ item }}" class="edit" href="{% url "admin:geartracker_item_change" item.id %}">Edit</a>
    {% endif %}

    <ul class="breadcrumb">
        <li><a href="{% url "geartracker_category_detail" slug=item.category.slug  %}" title="View all gear in {{ item.category }}">{{ item.category|capfirst }}</a> {{ item.type.separator }}</li>
        <li><a href="{% url "geartracker_type_detail" category=item.category.slug slug=item.type.slug %}" title="View all gear in {{ item.type.name }}">{{ item.type.name|capfirst }}</a></li>
    </ul>

    {% if item.image %}
        {% thumbnail item.image "400" as im %}
        <a class="item-image" href="{{ item.image.url }}" title="View full size image"><img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="Photo of {{ item }}"></a>
        {% endthumbnail %}
    {% endif %}

    <ul id="gear-details">
        <li class="weight">
            <h2>Weight</h2>
            <p><span class="item-weight-metric">{{ item.metric_weight }}</span> <span class="item-weight-imperial">{{ item.imperial_weight }}</span></p>
        </li>
        {% if item.size %}
        <li class="size">
            <h2>Size</h2>
            <p>{{ item.size }}</p>
        </li>
        {% endif %}
        <li class="acquired">
            <h2>Acquired</h2>
            <p>{{ item.acquired }}</p>
        </li>
        {% if item.review_url %}
        <li>
            <h2>Review</h2>
            <p><a href="{{ item.review_url }}" title="Read a review of the {{ item }}">Read a review</a>.</p>
        </li>
        {% endif %}
        {% if item.notes %}
        <li class="notes">
            <h2>Notes</h2>
            {{ item.notes|safe|linebreaks }}
        </li>
        {% endif %}
        {% if item.tags.all %}
        <li class="tags">
            <h2>Tags</h2>
            <ul>
                {% for tag in item.tags.all %}
                <li><a href="{% url "geartracker_tag_detail" slug=tag.slug %}" rel="tag" title="View all gear tagged with {{ tag }}">{{ tag }}</a></li>
                {% endfor %}
            </ul>
        </li>
        {% endif %}
        {% if item.related.all %}
        <li class="related">
            <h2>Related Items</h2>
            <ul>
                {% for other in item.related.all %}
                <li><a href="{% url "geartracker_item_detail" slug=other.slug %}" title="Link to {{ other }}" rel="bookmark">{{ other }}</a></li>
                {% endfor %}
            </ul>
        </li>
        {% endif %}
    </ul>
{% endblock %}

geartracker/templates/geartracker/item_list.html
{% extends "geartracker/base_geartracker.html" %}

{% block title %}Gear{% if is_paginated %} (Page {{ page_obj.number }}){% endif %} | {{ block.super }}{% endblock %}
{% block description %}{{ object_list|length }} item{{ object_list|pluralize }} in the database{% endblock %}
{% block body_id %}geartracker-gear-list{% endblock %}

{% block content %}
    <h1>Gear</h1>
    {% include "geartracker/includes/list_items.html" %}
{% endblock %}

geartracker/templates/geartracker/items_list.html
{% if item_list %}
<ul id="items">
    {% for item in item_list %}
        <li>
            <h2><a href="{% url geartracker_item_detail item.slug %}" rel="bookmark" title="Link to {{ item }}">{{ item }}</a></h2>
            <dl class="item-brief">
                <dt>Metric Weight</dt>
                    <dd>{{ item.metric_weight }}</dd>
                <dt>Imperial Weight</dt>
                    <dd>{{ item.imperial_weight }}</dd>
                <dt>Acquired</dt>
                    <dd>{{ item.acquired }}</dd>
            </dl>
        </li>
    {% endfor %}
</ul>
{% else %}
<p>No items found!</p>
{% endif %}

geartracker/templates/geartracker/list_detail.html
{% extends "geartracker/base_geartracker.html" %}

{% block title %}{{ list }} | {{ block.super }}{% endblock %}
{% block description %}List of gear taken on {{ list }} ({{ list.total_metric_weight }}, {{ list.total_imperial_weight }}){% endblock %}
{% block body_class %}geartracker-list{% endblock %}
{% block body_id %}geartacker-list-{{ list.id }}{% endblock %}

{% block content %}
    <h1>{{ list }}</h1>

    {% if perms.geartracker.change_item %}
    <a title="Edit {{ list }}" class="edit" href="{% url "admin:geartracker_list_change" list.id %}">Edit</a>
    {% endif %}

    <p id="trip-date">
    {% spaceless %}
    {% if list.start_date = list.end_date %}
    {{ list.start_date }}
    {% else %}
    {{ list.start_date }} &#8211; {{ list.end_date }}
    {% endif %}
    {% endspaceless %}
    </p>

    {% if list.location or list.trip_report %}
    <dl>
        {% if list.location %}
        <dt>Location:</dt>
            <dd>{{ list.location|safe }}</dd>
        {% endif %}
        {% if list.trip_report %}
        <dt>Report:</dt>
            <dd><a href="{{ list.trip_report }}" title="Read the trip report">Trip Report</a></dd>
        {% endif %}
    </dl>
    {% endif %}

    <div class="list-details">
        {% if worn_items %}
        <div class="worn-items">
            <h2>Worn Items</h2>
            {% with list=worn_items metric_weight=list.worn_metric_weight imperial_weight=list.worn_imperial_weight %}
                {% include "geartracker/includes/list_table.html" %}
            {% endwith %}
        </div>
        {% endif %}

        {% if packed_items %}
        <div class="packed-items">
            <h2>Packed Items</h2>
            {% with list=packed_items metric_weight=list.packed_metric_weight imperial_weight=list.packed_imperial_weight %}
                {% include "geartracker/includes/list_table.html" %}
            {% endwith %}
        </div>
        {% endif %}

        <h2>Total Weight</h2>
        <p id="the-total">{{ list.total_metric_weight }} ({{ list.total_imperial_weight }})</p>
    </div>
{% endblock %}

geartracker/templates/geartracker/list_list.html
{% extends "geartracker/base_geartracker.html" %}

{% block title %}Gear Lists{% if is_paginated %} (Page {{ page_obj.number }}){% endif %} | {{ block.super }}{% endblock %}
{% block description %}{{ list_list|length }} list{{ item_list|pluralize }} in the database{% endblock %}
{% block body_id %}geartracker-list-list{% endblock %}

{% block content %}
    <h1>Gear Lists</h1>
    {% include "geartracker/includes/list_lists.html" %}
{% endblock %}

geartracker/templates/geartracker/lists_list.html
{% if list_list %}
<ul id="lists">
    {% for list in list_list %}
        <li>
            <h2><a href="{% url geartracker_list_detail list.slug %}" rel="bookmark" title="Link to {{ list }}">{{ list }}</a></h2>
            <dl class="list-brief">
                <dt>Date{% if list.start_date != list.end_date %}s{% endif %}</dt>
                    <dd>{% spaceless %}
                    {% if list.start_date = list.end_date %}
                    {{ list.start_date }}
                    {% else %}
                    {{ list.start_date }} &#8211; {{ list.end_date }}
                    {% endif %}
                    {% endspaceless %}</dd>
                <dt>Total Weight</dt>
                    <dd>{{ list.total_metric_weight }} ({{ list.total_imperial_weight }})</dd>
            </dl>
        </li>
    {% endfor %}
</ul>
{% if is_paginated %}

<ul class="page-list">
    {% for pages in page_range %}
    <li {% if page = pages %}class="current"{% endif %}><a href="{% url lists_paginated page=pages %}" title="Page {{ pages }}">{{ pages }}</a></li>
    {% endfor %}
</ul>
{% endif %}
{% else %}
<p>No gear lists available!</p>
{% endif %}

geartracker/templates/geartracker/tag_detail.html
{% extends "geartracker/base_geartracker.html" %}

{% block title %}{{ tag }}{% if is_paginated %} (Page {{ page }}){% endif %} | {{ block.super }}{% endblock %}
{% block description %}{{ object_list|length }} item{{ object_list|pluralize }} tagged with {{ tag }}{% endblock %}
{% block body_id %}geartracker-tag-list{% endblock %}

{% block content %}
    <h1>{{ tag }}</h1>
    {% include "geartracker/includes/list_items.html" %}
{% endblock %}

geartracker/templates/geartracker/tag_list.html
{% extends "geartracker/base_geartracker.html" %}

{% load taggit_extras %}

{% block title %}Tags | {{ block.super }}{% endblock %}
{% block description %}Gear tags{% endblock %}
{% block body_id %}geartracker-tag-list{% endblock %}

{% block content %}
    <h1>Tags</h1>

    {% get_taglist as tags for 'geartracker.item' %}
    {% if tags %}
    <ul class="tags">
        {% for tag in tags %}
            <li><a href="{% url "geartracker_tag_detail" slug=tag.slug %}" title="View all gear tagged with {{ tag }}">{{ tag }}</a> ({{ tag.num_times }})</li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No tags available!</p>
    {% endif %}
{% endblock %}

geartracker/templates/geartracker/type_detail.html
{% extends "geartracker/base_geartracker.html" %}

{% block title %}{{ category|capfirst }} {{ type.separator }} {{ type.name|capfirst }}{% if is_paginated %} (Page {{ page }}){% endif %} | {{ block.super }}{% endblock %}
{% block description %}{{ object_list|length }} item{{ object_list|pluralize }} of type {{ type }}{% endblock %}
{% block body_id %}geartracker-type-list{% endblock %}

{% block content %}
    <h1>{{ type|capfirst }}</h1>
    {% include "geartracker/includes/list_items.html" %}
{% endblock %}